const router = require('express').Router()
const config = require('./config')
const user = require('./user')
const login = require('./login')
const post = require('./post')
const comment = require('./comment')
const like = require('./like')

//라우터 모음
router.all('/*', config.CORS)
router.get('/user', post.get_user)
router.post('/register', user.register)
router.post('/login', login.login)
router.get('/post', post.post)
router.get('/post/:postId', post.select)
router.post('/write', post.write)
router.put('/post/:postId', post.post_update)
router.delete('/post/:postId', post.post_delete)
router.get('/like/:postId', like.like_get)
router.post('/like/:postId', like.like_post)
router.get('/comment/:postId', comment.select)
router.post('/comment/:postId', comment.write)
router.put('/comment/:commentId', comment.update)
router.delete('/comment/:commentId', comment.remove)

module.exports = router
